Implement Vectorize GA binding changes
cloudflare/workerd pull request #2443
Opened 2024-07-25 16:21 UTC by ndisidore

Sister to https://github.com/cloudflare/workerd/pull/2421

This actually implements the new types, so the binding should be available for use.

2024-07-25 16:24 UTC, ndisidore commented on src/cloudflare/internal/vectorize-v2-api.ts
Not super excited about this having a `-v2-` in this path.
With wrapped bindings, I'm not 100% sure how dynamic they are..
If we were to move the existing `vectorize-api` to `vectorize-beta-api` and promote this to `vectorize-api`, I'm not sure if it would break existing users or if they would be okay since things are build at compile time.

2024-07-25 17:54 UTC, ndisidore commented on src/cloudflare/internal/vectorize-v2-api.ts
Confirmed with the runtime team that we can't rename existing modules and have them continue to work, so we may have to live with this (and not really that big of a deal)

2024-07-25 21:05 UTC, mikea requested changes

2024-07-25 21:05 UTC, mikea commented on src/cloudflare/internal/vectorize-v2-api.ts
> Confirmed with the runtime team that we can't rename existing modules and have them continue to work, so we may have to live with this (and not really that big of a deal)

It is true that if you change your module name, then existing pipeline will break. There are two ways out of this:

- create `-v2-` binding as you did with its own consequences
- make existing binding confrom to both standards by using version switch.

Since I'd prefer us not to have a copy of vectorize-api.ts, let me expand on it a little:

You change your api to look like:

```
export function makeBinding(env: {
  fetcher: Fetcher;
  indexId: string;
  version?: "v2";
}) {
}
```

and make your implementation respect version value. Now old pipelines won't have version at all, so you will fall back to the old implementation.

New pipelines will have "v2" version inner binding specified and will trigger new behavior.

You will have to change the way new pipelines are generated, so I'd rather you added version in there rather
that copies of api, unless changes are so drastic, which they are not.

As for types, I think only current path needs to be properly typed. Old path can use "any" all the way it wants.

2024-07-25 22:32 UTC, ndisidore commented on src/cloudflare/internal/vectorize-api.ts
> + * The Vectorize beta VectorizeIndex shares the same methods, so to keep things simple, they share one implementation.
This is what we discussed @mikea and I this holds true, I think we're happy with this approach!

2024-07-25 23:25 UTC, ndisidore commented on src/cloudflare/internal/vectorize-api.ts
> +  indexVersion?: "v2";
IIRC capn'p has a `number` type so this must be a string

2024-07-26 13:06 UTC, mikea approved these changes

2024-07-26 14:14 UTC, ndisidore commented on src/cloudflare/internal/vectorize-api.ts
> +      this.indexVersion === "v2" ? `info` : `binding/indexes/${this.indexId}`;
For v2, account info and index id are included in the base url of the fetcher so these endpoints just become the final path part.

2024-07-26 14:22 UTC, ndisidore commented on src/cloudflare/internal/vectorize-api.ts
> +    env.indexVersion ?? "v1"
This ensures backwards compatibility, since previously built pipelines won't have these inner globals.
We default to v1 if is it not present.

2024-07-26 16:46 UTC, merged