call synctime when receiving new websocket messages
cloudflare/workerd pull request #2623
Opened 2024-08-28 13:47 UTC by Frederik-Baetens

This seems safe to me since I don't really see a fundamental difference between websocket messages and fetch requests, and I think the hibernatable path already ends up calling synctime because I think it calls into IoContext::IncomingRequest::delivered() through HibernatableWebSocketCustomEventImpl::run().

I think you may be able to get more accurate timestamps by sending messages to a websocket pair that you just hold in a worker internally, but I think you may already be able to do that with hibernatable websockets?

2024-08-28 14:02 UTC, Frederik-Baetens commented
I'm not sure if this should be wrapped in:

```
KJ_IF_SOME(a, contexts.getActor()) {
  ioChannelFactory->getTimer().syncTime();
}
```

`IoContext::IncomingRequest::delivered()` does that, but I'm not sure what the benefit of doing that is.

2024-08-28 21:47 UTC, kentonv commented
This is almost certainly already happening somewhere else in the stack. This doesn't belong in code specific to one event type.

2024-08-28 21:50 UTC, kentonv requested changes
Yeah, syncTime() already happens as part of `context.run()` which is called a few lines later.

2024-08-28 21:51 UTC, kentonv commented
https://github.com/cloudflare/workerd/blob/main/src/workerd/io/io-context.c%2B%2B#L1003

2024-08-28 22:19 UTC, Frederik-Baetens commented
Thanks kenton, missed that.

2024-08-29 11:08 UTC, kentonv commented
I suppose we should close this, then.

2024-08-29 11:08 UTC, closed without merging