refactor zlib to simplify our implementation
cloudflare/workerd pull request #2679
Opened 2024-09-09 20:07 UTC by anonrig

A little bit late to the party but, I'm following up to @jasnell's comment on `context()`

2024-09-09 20:09 UTC, jasnell approved these changes

2024-09-09 22:08 UTC, npaun commented on src/workerd/api/node/zlib-util.h
> +      return *&context;
```suggestion
      return context;
```

2024-09-11 21:08 UTC, npaun requested changes

2024-09-11 21:08 UTC, npaun commented on src/workerd/api/node/zlib-util.h
> +    CompressionContext context;
This creates a use-after-free error because allocations will be destroyed before context.

2024-09-11 21:11 UTC, closed without merging