Add Email types
cloudflare/workerd pull request #277
Opened 2023-01-17 15:17 UTC by nelsonjsduarte

- EmailMessage
- EmailEvent
- EmailExportedHandler

2023-01-17 15:22 UTC, nelsonjsduarte commented
I have read the CLA Document and I hereby sign the CLA

2023-01-17 15:24 UTC, jasnell approved these changes

2023-01-18 11:11 UTC, edevil requested changes

2023-01-18 11:11 UTC, edevil commented on types/defines/email.d.ts
> +  readonly from: string;
"Envelope From attribute of the email message."

2023-01-18 11:11 UTC, edevil commented on types/defines/email.d.ts
> +   * A envelope to.
"Envelope To attribute of the email message."

2023-01-18 11:11 UTC, edevil commented on types/defines/email.d.ts
> +   * Size of the raw email message content.
"Size of the email message content."

2023-01-18 11:11 UTC, edevil commented on types/defines/email.d.ts
> +   * Reject email message
"Reject this email message by returning a permanent SMTP error back to the connecting client including the given reason."

2023-01-18 11:11 UTC, edevil commented on types/defines/email.d.ts
> +   * Forward email message to a verified destination address.
"Forward this email message to a verified destination address of the account."

2023-01-18 11:11 UTC, edevil commented on types/defines/email.d.ts
> +   * @returns A promise that resolves when the email message is forward
"A promise that resolves when the email message is forwarded."

2023-01-18 11:31 UTC, edevil approved these changes

2023-01-19 12:35 UTC, merged