Use name instead of id for instances in Workflows binding
cloudflare/workerd pull request #2881
Opened 2024-10-09 20:08 UTC by sidharthachatterjee

This is a breaking chance but the binding is currently experimental so that is okay 

The Workflow binding currently accepts an `id` for its create and get functions. We now allow users to pass in a user defined "instance name". This can be used to lookup instances that were previously created.

2024-10-09 20:40 UTC, jasnell approved these changes

2024-10-10 08:26 UTC, LuisDuarte1 requested changes

2024-10-10 08:26 UTC, LuisDuarte1 commented on types/defines/workflows.d.ts
> +  public create(name: string, params: object): Promise<Instance>;
I think it would be better to create a `CreateInstanceParams` interface, to allow for better extensibility (we are making breaking changes anyway)

2024-10-10 08:26 UTC, LuisDuarte1 commented on types/defines/workflows.d.ts
> +  public create(name: string, params: object): Promise<Instance>;
`params` should be unknown and not an objext

2024-10-17 19:31 UTC, LuisDuarte1 approved these changes

2024-10-22 13:38 UTC, closed without merging