SQC-333: Support Hyperdrive with SSL in dev mode
cloudflare/workerd pull request #3037
Opened 2024-10-31 16:41 UTC by ReppCodes

We have historically used sslmode=disable in when running `wrangler dev`, with the intention of not forcing folks to set up SSL on a local test DB.  Unfortunately this causes friction because many hosted databases will have SSL set up and required, and Hyperdrive in production actually requires this. To improve flexibilty, switch to `prefer` mode which will use SSL if available for a close-to-production experience, but will allow unencrypted connections if needed.

2024-10-31 16:49 UTC, ReppCodes commented
I have read the CLA Document and I hereby sign the CLA

2024-10-31 17:00 UTC, thomasgauvin requested changes
This means folks won't be able to connect without ssl

2024-10-31 17:01 UTC, thomasgauvin approved these changes

2024-10-31 17:29 UTC, a-robinson approved these changes

2024-11-03 23:48 UTC, jasnell approved these changes

2024-11-05 14:02 UTC, anonrig approved these changes

2024-11-05 14:03 UTC, merged