chore(readme): fix typo
cloudflare/workerd pull request #36
Opened 2022-09-27 16:43 UTC by millsp

2022-09-27 17:56 UTC, ocdtrekkie approved these changes
Glad I checked the PR tab before opening my own!

2022-09-27 18:03 UTC, ocdtrekkie commented on README.md
> +`workerd` tries to isolate each Worker so that it can only access the resources it is configured to access. However, `workerd` on its own does not contain suitable defense-in-depth against the possib
Heh, wow, I failed to check the typo fix for a typo. Nice catch, @jclee

2022-09-27 18:04 UTC, ocdtrekkie requested changes
Unapprove, see jclee's comment

2022-09-28 12:27 UTC, millsp commented on README.md
> +`workerd` tries to isolate each Worker so that it can only access the resources it is configured to access. However, `workerd` on its own does not contain suitable defense-in-depth against the possib
:see_no_evil: Thanks

2022-09-28 14:49 UTC, jasnell approved these changes

2022-09-28 21:25 UTC, merged

2022-09-28 21:26 UTC, kentonv commented
Thanks!