Implement per IoContext request ID
cloudflare/workerd pull request #750
Opened 2023-06-08 18:52 UTC by jasnell

Assigns every IoContext a unique uuid and makes it available via async context tracking to the worker via a new cloudflare:request-context import.

The purpose here is to ensure that every unhandledrejection event can be properly associated with the particular IoContext within which it was triggered.

For example, if we take the following example, in which multiple requests try to await on a cross-request i/o promise (which is currently not permitted)... the `'unhandledrejection'` event will not report the correct request ID... This is because the promise that is actually rejected exists outside the scope of the workers `async fetch() ...` handler and the `store` value is correctly `undefined` in the handler.

```js
let promise;
let workerId;

import { AsyncLocalStorage } from 'node:async_hooks';

const storage = new AsyncLocalStorage();

export default {
  async fetch() {
    workerId ||= crypto.randomUUID();
    const requestId = crypto.randomUUID();

    promise ||= (() => {
      console.log('fetching');
      return storage.run({ workerId, requestId }, async () => {
        return await fetch('https://example.vercel.sh/');
      });
    })();
    await storage.run({ requestId, workerId }, async () => await promise);
    return new Response(`Hello from ${workerId}!`);
  },
};

addEventListener('unhandledrejection', event => {
  const store = storage.getStore();
  console.log('unhandled', event.reason, 'store', store);
});
```

However, by introducing an internal request ID mechanism we can appropriately attribute the unhandled rejection to the request in which it was actually triggered:

```js
let promise;
let workerId;

import { getRequestId } from 'cloudflare:request-context';
import { AsyncLocalStorage } from 'node:async_hooks';

const storage = new AsyncLocalStorage();

console.log(getRequestId()); // returns undefined since we're not in a request.

export default {
  async fetch() {
    console.log(getRequestId()); // returns this requests unique id.
    promise ||= (() => {
      console.log('fetching');
      return await fetch('https://example.vercel.sh/');
    })();
    await promise;
    return new Response(`Hello from ${workerId}!`);
  },
};

addEventListener('unhandledrejection', event => {
  // here getRequestId() will return the id associated with the request that scheduled 
  // the fetch, which is the request context we're in when the unhandledrejection occurs.
  console.log('unhandled', event.reason, 'store', getRequestId());
});
```

2023-06-08 19:35 UTC, kentonv requested changes
This is introducing a new public API concept which we will forever have to support and educate users about, in order to solve a very specific problem. We need to have a careful discussion about whether this is the right approach -- there should be a design doc and stuff and a chance for more people to provide feedback. Adding new APIs should not happen on a whim in a code review.

From what I can see, I don't understand why this is needed. The specific problem is that unhandled rejection events don't run in the correct async context. Can we just fix that, so that they do run in the connect async context? That would be much more friendly to our users, wouldn't it?

2023-06-08 19:36 UTC, kentonv commented
> This is because the promise that is actually rejected exists outside the scope of the workers async fetch() ... handler and the store value is correctly undefined in the handler.

Can you explain this more? What is "the promise that is actually rejected" and why is it not in the relevant context?

2023-06-08 19:48 UTC, kentonv commented
I don't see any tests here nor in the internal PR. Are you sure it works?

It looks to me like this is depending on and exposing the very, very weird behavior of cross-request promises in our system. In the unhandledrejection handler `getRequestId()` will return the ID of the request which originally initiated the fetch, _not_ the request which logically created the promise that ended up rejected. This is only because the promise was incorrectly continued within the scope of the wrong request. Arguably if we wanted to fix this we would tag promises with the request that created them, and make sure when a promise is waited on from some other request, we do the appropriate cross-request synchronization. But that would actually alter the behavior here, seemingly...

2023-06-08 20:35 UTC, jasnell commented
> Adding new APIs should not happen on a whim in a code review.

Nothing here is being added "on a whim". Please do not imply that simply because a proposal is made in PR form that it has not been thought out as that's just simply not helpful. This PR *is* the proposal. If we decide that this isn't the direction we want to take we can simply close this PR.

> ... We need to have a careful discussion about whether this is the right approach

I agree. Please feel free to discuss this proposed approach as much as necessary.

> I don't see any tests here nor in the internal PR. Are you sure it works as you intended?

Yes it works, at least for this particular test case. Once we're sure this is the direction to take, I will put in the additional effort to implement the necessary tests to prove that it works in all relevant cases. I'll convert this to a draft PR until that time so that it's clear.

> From what I can see, I don't understand why this is needed. The specific problem is that unhandled rejection events don't run in the correct async context. Can we just fix that, so that they do run in the connect async context? That would be much more friendly to our users, wouldn't it?

What is the correct async context for this particular unhandled rejection event to run in? Where is that established? How does it connect to the `AsyncLocalStorage` instance used within the fetch handler?

The specific problem in this test case is that the promise rejection happens outside the scope of the fetch handler where the users `AsyncLocalStorage` is entered. The `unhandledrejection` handler already *does* run in the correct async context, it's just not a context that has any visibility to the `AsyncLocalStorage` instance that is used in the fetch handler. The promises created on and waited within that `AsyncLocalStorage` run --that is, the fetch promise and the awaits -- are not the promises that are rejected and therefore are not the promise that is notified about in the unhandledrejection event handler.

> It looks to me like this is depending on and exposing the very, very weird behavior of cross-request promises in our system. In the unhandledrejection handler getRequestId() will return the ID of the request which originally initiated the fetch, not the request which logically created the promise that ended up rejected. This is only because the promise was incorrectly continued within the scope of the wrong request. Arguably if we wanted to fix this we would tag promises with the request that created them, and make sure when a promise is waited on from some other request, we do the appropriate cross-request synchronization. But that would actually alter the behavior here, seemingly...

Keep in mind that `unhandledrejection`s propagate the async context that is current *at the moment of rejection* and not at the point the promise was created. Since, in this particular case, the rejection is happening in the IoContext that originated the fetch (since that is where the IoOwn check is throwing) that is the ID that is captured and propagated. And yes, this does present a challenge for cross-request promises in general, but that's not a new problem.

We currently do not track the creation of promises. In theory, we certainly could implement a more robust handling for cross-request promises here using the Promise hooks API. It wouldn't change the behavior of this proposed new `getRequestId()` API (and doesn't negate it either) but could potentially change the specific async context the `unhandledrejection` handler propagates. If such a change was ever made then the change in behavior would require a compat flag.

Also, this particular problem is just one use case for the proposed `getRequestId()` API.

2023-06-27 14:42 UTC, kentonv commented
I am still uncomfortable with this API. I think it exposes internal implementation details while also feeling redundant vs. async context.

What is the need, now that we've enabled cross-context promise resolution? Can't people use async context to track which request they are in, if they so desire?

2023-06-27 15:11 UTC, closed without merging